spring:
  mail:
    host: smtp.163.com
    port: 25
    username: yjswc1076@163.com
    password:
##    加密方式，假如有需要写，没有就不写
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: true
#            required: true
mymail:
  email: yjswc1076@163.com