spring:
  application:
    name: gateway
  profiles:
    active: dev
#      静态文件映射
  mvc:
    static-path-pattern: /image/**
  resources:
#    这里同支付二维码存放位置
    static-locations: file:C:/Users/QING/Image/QRCODE/
  redisson:
    address: 127.0.0.1:6379
    database: 0
    timeout: 3000
    pool:
      max-active: 20
      max-idle: 10
      max-wait: 3000
      min-idle: 4
server:
  port: 8080
